// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.3
// source: market_overview_req.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//  市场概要信息请求
type MarketOverviewReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonReq  *CommonReq `protobuf:"bytes,1,opt,name=commonReq,proto3" json:"commonReq,omitempty"`    // 标准请求
	MarketType int32      `protobuf:"varint,2,opt,name=marketType,proto3" json:"marketType,omitempty"` // 市场类型列表
	Version    uint32     `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`       //版本号
}

func (x *MarketOverviewReq) Reset() {
	*x = MarketOverviewReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_overview_req_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketOverviewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketOverviewReq) ProtoMessage() {}

func (x *MarketOverviewReq) ProtoReflect() protoreflect.Message {
	mi := &file_market_overview_req_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketOverviewReq.ProtoReflect.Descriptor instead.
func (*MarketOverviewReq) Descriptor() ([]byte, []int) {
	return file_market_overview_req_proto_rawDescGZIP(), []int{0}
}

func (x *MarketOverviewReq) GetCommonReq() *CommonReq {
	if x != nil {
		return x.CommonReq
	}
	return nil
}

func (x *MarketOverviewReq) GetMarketType() int32 {
	if x != nil {
		return x.MarketType
	}
	return 0
}

func (x *MarketOverviewReq) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_market_overview_req_proto protoreflect.FileDescriptor

var file_market_overview_req_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x76, 0x69, 0x65,
	0x77, 0x5f, 0x72, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x1a, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x11, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x4f, 0x76,
	0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x12, 0x2e, 0x0a, 0x09, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x52, 0x09,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_market_overview_req_proto_rawDescOnce sync.Once
	file_market_overview_req_proto_rawDescData = file_market_overview_req_proto_rawDesc
)

func file_market_overview_req_proto_rawDescGZIP() []byte {
	file_market_overview_req_proto_rawDescOnce.Do(func() {
		file_market_overview_req_proto_rawDescData = protoimpl.X.CompressGZIP(file_market_overview_req_proto_rawDescData)
	})
	return file_market_overview_req_proto_rawDescData
}

var file_market_overview_req_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_market_overview_req_proto_goTypes = []interface{}{
	(*MarketOverviewReq)(nil), // 0: model.MarketOverviewReq
	(*CommonReq)(nil),         // 1: model.CommonReq
}
var file_market_overview_req_proto_depIdxs = []int32{
	1, // 0: model.MarketOverviewReq.commonReq:type_name -> model.CommonReq
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_market_overview_req_proto_init() }
func file_market_overview_req_proto_init() {
	if File_market_overview_req_proto != nil {
		return
	}
	file_common_req_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_market_overview_req_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketOverviewReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_market_overview_req_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_overview_req_proto_goTypes,
		DependencyIndexes: file_market_overview_req_proto_depIdxs,
		MessageInfos:      file_market_overview_req_proto_msgTypes,
	}.Build()
	File_market_overview_req_proto = out.File
	file_market_overview_req_proto_rawDesc = nil
	file_market_overview_req_proto_goTypes = nil
	file_market_overview_req_proto_depIdxs = nil
}
