// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.3
// source: number_wrapper.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 跟数字相关的对象封装
type NumberWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value   int64  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`     // 转换成整数之后的数字
	Decimal uint32 `protobuf:"varint,2,opt,name=decimal,proto3" json:"decimal,omitempty"` // 3表示扩大 10^3 = 1000倍
}

func (x *NumberWrapper) Reset() {
	*x = NumberWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_number_wrapper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberWrapper) ProtoMessage() {}

func (x *NumberWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_number_wrapper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberWrapper.ProtoReflect.Descriptor instead.
func (*NumberWrapper) Descriptor() ([]byte, []int) {
	return file_number_wrapper_proto_rawDescGZIP(), []int{0}
}

func (x *NumberWrapper) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *NumberWrapper) GetDecimal() uint32 {
	if x != nil {
		return x.Decimal
	}
	return 0
}

var File_number_wrapper_proto protoreflect.FileDescriptor

var file_number_wrapper_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x3f, 0x0a,
	0x0d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_number_wrapper_proto_rawDescOnce sync.Once
	file_number_wrapper_proto_rawDescData = file_number_wrapper_proto_rawDesc
)

func file_number_wrapper_proto_rawDescGZIP() []byte {
	file_number_wrapper_proto_rawDescOnce.Do(func() {
		file_number_wrapper_proto_rawDescData = protoimpl.X.CompressGZIP(file_number_wrapper_proto_rawDescData)
	})
	return file_number_wrapper_proto_rawDescData
}

var file_number_wrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_number_wrapper_proto_goTypes = []interface{}{
	(*NumberWrapper)(nil), // 0: model.NumberWrapper
}
var file_number_wrapper_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_number_wrapper_proto_init() }
func file_number_wrapper_proto_init() {
	if File_number_wrapper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_number_wrapper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_number_wrapper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_number_wrapper_proto_goTypes,
		DependencyIndexes: file_number_wrapper_proto_depIdxs,
		MessageInfos:      file_number_wrapper_proto_msgTypes,
	}.Build()
	File_number_wrapper_proto = out.File
	file_number_wrapper_proto_rawDesc = nil
	file_number_wrapper_proto_goTypes = nil
	file_number_wrapper_proto_depIdxs = nil
}
