version: "3.8"
services:
  crawler:
    build:
      context: .
      args:
        - ENV=development # 指定开发环境构建
    image: quatt_watchdog:latest
    container_name: quatt_watchdog
    environment:
      - ENV=development
      - CRAWL_INTERVAL=5m
      - TARGET_URLS=https://example.com,https://another-example.com
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - TCP_SRV_HOST=${TCP_SRV_HOST}
      - TCP_SRV_U_ID=${TCP_SRV_U_ID}
      - TCP_SRV_U_DEVICE_ID=${TCP_SRV_U_DEVICE_ID}
      - TCP_SRV_TOKEN=${TCP_SRV_TOKEN}
    volumes:
      - .:/workdir # 将本地代码挂载到容器中，如果是production，则这个不需要
      - /var/log/app_docker:/var/log/app
